#ifndef NAME_SCHEMATIC_H
#define NAME_SCHEMATIC_H

// Constants
#define ENCODER_TIME 0.1
#define MAX_SPEED 1
#define PRINT_TIME 0.1
#define RAMP_SPEED 0.1
#define DEADBAND 0.1
#define TRUSS_ENCODER_SPOT 0

// Settings
#define COLLECTOR_MOTOR_OUT -1
#define COLLECTOR_MOTOR_STOP 0
#define COLLECTOR_MOTOR_IN 1
#define LOW_GEAR 1
#define HIGH_GEAR 0
#define LATCH_ON 0
#define LATCH_OFF 1
#define SHOOT_SHIFT_NEUTRAL 1
#define SHOOT_SHIFT_GEAR 0
#define SHOOT_LIMIT_HIT 1
#define SHOOTER_AUTO 1
#define SHOOTER_MANUAL 0
#define SHOOTER_MANUAL_WINCH_SPEED 0.75

// Shooter Points

#define SHOOTER_LATCH_POINT_OFFSET 0
#define SHOOTER_LATCH_OFF_POINT_OFFSET 75
#define SHOOTER_TRUSS_POINT_OFFSET -500
#define SHOOTER_GOAL_POINT_OFFSET -100
#define SWITCH_TO_LIMIT_SWITCH_VALUE -200

#define INITIALAIZE_SHOOTER 0
#define MOVE_TO_GOAL_POINT 1
#define SHIFT_MOTOR_TO_NEUTRAL 2
#define WAIT_FOR_COMMAND 3
#define SHOOT_THE_BALL 4
#define WINCH_MOTOR_TO_GEAR 5
#define RETRACT_ARM 6
#define RELATCH_ARM 7
#define WINCH_TO_LIMIT_SWITCH 8

#define WINCH_DOWN -1
#define WINCH_UP 1

// Stuff
#define ON 1
#define OFF 0
#define PRESSED 1
#define NOT_PRESSED 0

// camera
#define CAMERA_IP_ADDRESS "10.5.37.11"
#define YELLOW_PIXEL_THRESHOLD 2000

#endif
